server:
  port: 8094

spring:
  application:
    name: map-service

logging:
  config: classpath:logback-spring.xml
  file:
    path: /Users/sx/Documents/workSpace/didi-taxi/map/logs/map-service

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://127.0.0.1:9411/api/v2/spans

