server:
  port: 8101

spring:
  application:
    name: driver-api

logging:
  config: classpath:logback-spring.xml
  file:
    path: /Users/sx/Documents/workSpace/didi-taxi/driver-api/logs/driver-api

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://127.0.0.1:9411/api/v2/spans

services:
  order:
    base-url: http://127.0.0.1:8093
  passenger:
    base-url: http://127.0.0.1:8092
  capacity:
    base-url: http://127.0.0.1:8090
  calculate:
    base-url: http://127.0.0.1:8091

