CREATE TABLE IF NOT EXISTS company (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    city_code VARCHAR(32) NULL,
    city_name VARCHAR(64) NULL,
    company_no VARCHAR(32) NOT NULL,
    company_name VARCHAR(128) NOT NULL,
    team_id BIGINT NULL,
    team VARCHAR(128) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_deleted INT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS driver (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    driver_source INT NULL,
    city_code VARCHAR(32) NULL,
    city_name VARCHAR(64) NULL,
    company_id BIGINT NULL,
    brand_no VARCHAR(32) NULL,
    brand_name VARCHAR(128) NULL,
    name VARCHAR(64) NOT NULL,
    id_card VARCHAR(32) NOT NULL,
    id_card_photo_a VARCHAR(1024) NULL,
    id_card_photo_b VARCHAR(1024) NULL,
    phone VARCHAR(32) NOT NULL,
    gender INT NULL,
    birthday DATE NULL,
    nationality VARCHAR(64) NULL,
    nation VARCHAR(32) NULL,
    marital_status INT NULL,
    photo_oss VARCHAR(1024) NULL,
    with_car_photo VARCHAR(1024) NULL,
    license_photo_oss_a VARCHAR(1024) NULL,
    license_photo_oss_b VARCHAR(1024) NULL,
    get_driver_license_date DATE NULL,
    driver_license_on DATE NULL,
    driver_license_off DATE NULL,
    rpt_status INT NULL,
    monitor_status INT NULL,
    can_accept_order INT NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_deleted INT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS driver_team_change_request (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    driver_id BIGINT NOT NULL,
    from_company_id BIGINT NULL,
    to_company_id BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL,
    request_reason VARCHAR(512) NULL,
    requested_by VARCHAR(64) NULL,
    requested_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    reviewed_by VARCHAR(64) NULL,
    reviewed_at TIMESTAMP NULL,
    review_reason VARCHAR(512) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_deleted INT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS car (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    driver_id BIGINT NULL,
    brand_no VARCHAR(32) NULL,
    brand_name VARCHAR(128) NULL,
    city_code VARCHAR(32) NOT NULL,
    city_name VARCHAR(64) NULL,
    car_no VARCHAR(32) NOT NULL,
    plate_color VARCHAR(32) NULL,
    vehicle_type VARCHAR(64) NULL,
    owner_name VARCHAR(64) NULL,
    certify_date_a DATE NULL,
    fuel_type VARCHAR(32) NULL,
    photo_oss VARCHAR(1024) NULL,
    with_photo_oss VARCHAR(1024) NULL,
    ride_type_id VARCHAR(64) NOT NULL,
    business_type_id VARCHAR(64) NULL,
    car_state INT NULL,
    car_num INT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_deleted INT NOT NULL DEFAULT 0
);
