server:
  port: 8091

spring:
  application:
    name: calculate-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/calculate?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      validation-query: SELECT 1
      test-while-idle: true

logging:
  config: classpath:logback-spring.xml
  file:
    path: /Users/sx/Documents/workSpace/didi-taxi/calculate/logs/calculate-service

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath*:mapper/**/*.xml
