CREATE TABLE IF NOT EXISTS fare_rule (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    company_id BIGINT NOT NULL,
    company_no VARCHAR(32) NOT NULL,
    province_code VARCHAR(32) NOT NULL,
    city_code VARCHAR(32) NOT NULL,
    product_code VARCHAR(64) NOT NULL,
    rule_name VARCHAR(128) NULL,
    effective_from TIMESTAMP NOT NULL,
    effective_to TIMESTAMP NULL,
    base_fare DECIMAL(10, 2) NOT NULL,
    included_distance_km DECIMAL(10, 2) NOT NULL DEFAULT 0,
    included_duration_min INT NOT NULL DEFAULT 0,
    per_km_price DECIMAL(10, 2) NOT NULL DEFAULT 0,
    per_minute_price DECIMAL(10, 2) NOT NULL DEFAULT 0,
    minimum_fare DECIMAL(10, 2) NULL,
    maximum_fare DECIMAL(10, 2) NULL,
    is_deleted INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
