spring:
  config:
    import:
      - nacos:calculate-service-local.yml?group=DIDI_TAXI&refreshEnabled=false
  nacos:
    config:
      server-addr: "${NACOS_SERVER_ADDR:127.0.0.1:8848}"
      namespace: "${NACOS_NAMESPACE}"
      username: "${NACOS_USERNAME:nacos}"
      password: "${NACOS_PASSWORD}"
